# Generated by Django 4.2.6 on 2023-11-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Serrurier", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avis",
            old_name="date_created",
            new_name="date_posted",
        ),
        migrations.AlterField(
            model_name="avis",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
            ),
        ),
    ]
